#!/bin/bash
set -e


# 1. 检查并配置 JAVA 相关环境变量
if [ -z "${JAVA_VERSION}" ]; then
    echo "Error: Environment variable JAVA_VERSION is not set."
    exit 1
fi

TARGET_JAVA_HOME="/opt/runtime/jre-${JAVA_VERSION}"
TARGET_JAVA_BIN="${TARGET_JAVA_HOME}/bin/java"

# (1) 检查 JAVA_HOME 目录是否存在
if [ ! -d "${TARGET_JAVA_HOME}" ]; then
    echo "Error: JAVA_HOME directory not found at: ${TARGET_JAVA_HOME}"
    exit 1
fi

# (2) 检查 Java 二进制文件是否存在且具有执行权限
if [ ! -x "${TARGET_JAVA_BIN}" ]; then
    echo "Error: Java executable not found or not executable at: ${TARGET_JAVA_BIN}"
    exit 1
fi

export JAVA_HOME="${TARGET_JAVA_HOME}"
export PATH="${JAVA_HOME}/bin:$PATH"


# 2. 配置运行用户
PUID=${PUID:-1000}
PGID=${PGID:-1000}
CURRENT_PUID=$(id -u gsrv)
CURRENT_PGID=$(id -g gsrv)

# (1) UID/GID 重配置
if [ "$PUID" != "$CURRENT_PUID" ] || [ "$PGID" != "$CURRENT_PGID" ]; then
    # UID/GID 修正
    echo "INFO: Updating UID/GID..."
    groupmod -o -g "$PGID" gsrv
    usermod -o -u "$PUID" -g "$PGID" gsrv
    
    # 家目录权限修正
    echo "INFO: Fixing PrV on home directory (/opt/gsrv)..."
    chown -R gsrv:gsrv /opt/gsrv
fi


# 3. 切换目录并运行应用
WORKDIR="/app"
# (1) 存在性检查
if [ ! -d "${WORKDIR}" ]; then
    echo "Error: Working directory ${WORKDIR} does not exist."
    exit 1
fi

# (2) 权限检查
if ! gosu gsrv test -w "${WORKDIR}"; then
    echo "-----------------------------------------------------"
    echo "ERROR: User 'gsrv' (UID=$PUID) CANNOT write to /app."
    echo "Current /app owner: $(stat -c '%U:%G' /app)"
    echo ""
    echo "Fix suggestions:"
    echo "1. Set PUID/PGID to match the host directory owner."
    echo "2. Or chown the host directory: chown -R $PUID:$PGID ./data"
    echo "-----------------------------------------------------"
    exit 1
fi

cd "${WORKDIR}"
exec gosu gsrv "$@"